workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "api"
    - when: never

stages:
  - deploy

variables:
  APP: nws-app
  CONTAINER: nws-app
  IMAGE_NAME: nws-app
  IMAGE_TAG: latest
  COMPOSE_FILE: docker-compose.dev.yml
  COMPOSE_PROJECT_NAME: nws-app
  ENVIRONMENT: "dev"
  RESTART_ONLY: "false"
  ROLLBACK_SHA: ""

include:
  - local: ci-cd/deploy.yml
