export { deriveDetail } from './data'
export type { ClientDetail, Program } from './types'
export { IdentityPanel } from './components/IdentityPanel'
export { OverviewTab } from './components/OverviewTab'
export { LifetimePrograms } from './components/LifetimePrograms'
export { ProgramJourney } from './components/ProgramJourney'
export { NotesTab } from './components/NotesTab'
export { ActivityTab } from './components/ActivityTab'
