import {
  Activity,
  AlertTriangle,
  Anchor,
  ArrowLeft,
  ArrowRight,
  BarChart2,
  BatteryLow,
  Bell,
  Bold,
  Bot,
  Braces,
  Brain,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  CalendarRange,
  CalendarX,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardX,
  Clock,
  Cookie,
  Copy,
  CreditCard,
  Crop,
  Download,
  Droplet,
  Dumbbell,
  Eye,
  EyeOff,
  FileDown,
  FileText,
  Flag,
  Flame,
  GitBranch,
  GripVertical,
  Hand,
  HeartPulse,
  HelpCircle,
  Image,
  ImageOff,
  ImagePlus,
  Inbox,
  Info,
  Italic,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Leaf,
  LifeBuoy,
  Link,
  List,
  ListOrdered,
  Lock,
  LogOut,
  Mail,
  Maximize2,
  Megaphone,
  MessageCircle,
  MessageCircleOff,
  MessageSquareText,
  MilkOff,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointerClick,
  NotebookPen,
  NotebookText,
  OctagonX,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  Play,
  PlayCircle,
  Plus,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  Rows3,
  Save,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  ShoppingBasket,
  SkipForward,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Sunrise,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  Type,
  Underline,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserRound,
  UserX,
  Users,
  Utensils,
  Wand2,
  X,
  XCircle,
  type LucideProps,
  type LucideIcon,
} from 'lucide-react'

// Generated registry — kebab lucide name -> component, so ported markup can
// keep V2's data-lucide names. Only the icons the app uses are imported, so
// the bundle stays tree-shaken. Add new names here as screens are ported.
const ICONS: Record<string, LucideIcon> = {
  'activity': Activity,
  'alert-triangle': AlertTriangle,
  'anchor': Anchor,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'bar-chart-2': BarChart2,
  'battery-low': BatteryLow,
  'bell': Bell,
  'bold': Bold,
  'bot': Bot,
  'braces': Braces,
  'brain': Brain,
  'building-2': Building2,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'calendar-plus': CalendarPlus,
  'calendar-range': CalendarRange,
  'calendar-x': CalendarX,
  'check': Check,
  'check-check': CheckCheck,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle': Circle,
  'clipboard-check': ClipboardCheck,
  'clipboard-copy': ClipboardCopy,
  'clipboard-list': ClipboardList,
  'clipboard-x': ClipboardX,
  'clock': Clock,
  'cookie': Cookie,
  'copy': Copy,
  'credit-card': CreditCard,
  'crop': Crop,
  'download': Download,
  'droplet': Droplet,
  'dumbbell': Dumbbell,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-down': FileDown,
  'file-text': FileText,
  'flag': Flag,
  'flame': Flame,
  'git-branch': GitBranch,
  'grip-vertical': GripVertical,
  'hand': Hand,
  'heart-pulse': HeartPulse,
  'help-circle': HelpCircle,
  'image': Image,
  'image-off': ImageOff,
  'image-plus': ImagePlus,
  'inbox': Inbox,
  'info': Info,
  'italic': Italic,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'layout-template': LayoutTemplate,
  'leaf': Leaf,
  'life-buoy': LifeBuoy,
  'link': Link,
  'list': List,
  'list-ordered': ListOrdered,
  'lock': Lock,
  'log-out': LogOut,
  'mail': Mail,
  'maximize-2': Maximize2,
  'megaphone': Megaphone,
  'message-circle': MessageCircle,
  'message-circle-off': MessageCircleOff,
  'message-square-text': MessageSquareText,
  'milk-off': MilkOff,
  'moon': Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'mouse-pointer-click': MousePointerClick,
  'notebook-pen': NotebookPen,
  'notebook-text': NotebookText,
  'octagon-x': OctagonX,
  'paperclip': Paperclip,
  'pause': Pause,
  'pencil': Pencil,
  'phone': Phone,
  'play': Play,
  'play-circle': PlayCircle,
  'plus': Plus,
  'refresh-cw': RefreshCw,
  'repeat': Repeat,
  'rocket': Rocket,
  'rotate-ccw': RotateCcw,
  'rows-3': Rows3,
  'save': Save,
  'search': Search,
  'search-x': SearchX,
  'send': Send,
  'settings': Settings,
  'shield': Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shield-x': ShieldX,
  'shopping-basket': ShoppingBasket,
  'skip-forward': SkipForward,
  'sliders-horizontal': SlidersHorizontal,
  'smile': Smile,
  'sparkles': Sparkles,
  'star': Star,
  'stethoscope': Stethoscope,
  'sunrise': Sunrise,
  'tag': Tag,
  'target': Target,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'type': Type,
  'underline': Underline,
  'upload': Upload,
  'user': User,
  'user-check': UserCheck,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  'user-round': UserRound,
  'user-x': UserX,
  'users': Users,
  'utensils': Utensils,
  'wand-2': Wand2,
  'x': X,
  'x-circle': XCircle,
}

type IconProps = Omit<LucideProps, 'ref'> & { name: string }

export function Icon({ name, size = 18, ...props }: IconProps) {
  const Cmp = ICONS[name]
  if (!Cmp) return null
  return <Cmp size={size} {...props} />
}
